-- MySQL Script generated by MySQL Workbench
-- Sat Sep 24 16:09:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Prepodavateli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prepodavateli` (
  `idPrepodavateli` INT NOT NULL,
  `Familiya` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Otchestvo` VARCHAR(45) NULL,
  `Data rozhdenya` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Specialisaciya` VARCHAR(45) NULL,
  `Stazh raboti` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrepodavateli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facultet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facultet` (
  `idFacultet` INT NOT NULL,
  `Nazvanie faculteta` VARCHAR(45) NULL,
  `Sokrashennoe nazvanie` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`idFacultet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplini`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplini` (
  `idDisciplini` INT NOT NULL,
  `Nazvanie disciplini` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisciplini`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Yspevaemost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Yspevaemost` (
  `idYspevaemost` INT NOT NULL,
  `Familiya studenta` VARCHAR(45) NULL,
  `Name studenta` VARCHAR(45) NULL,
  `Otchestvo studenta` VARCHAR(45) NULL,
  `Gryppa` VARCHAR(45) NULL,
  `Disciplina` VARCHAR(45) NULL,
  `Ocenka za 1 semestr` VARCHAR(45) NULL,
  `Ocenka za 2 semestr` VARCHAR(45) NULL,
  `Sredniy bal` VARCHAR(45) NULL,
  `Disciplini_idDisciplini` INT NOT NULL,
  PRIMARY KEY (`idYspevaemost`, `Disciplini_idDisciplini`),
  INDEX `fk_Yspevaemost_Disciplini1_idx` (`Disciplini_idDisciplini` ASC) VISIBLE,
  CONSTRAINT `fk_Yspevaemost_Disciplini1`
    FOREIGN KEY (`Disciplini_idDisciplini`)
    REFERENCES `mydb`.`Disciplini` (`idDisciplini`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gryppi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gryppi` (
  `idGryppi` INT NOT NULL,
  `Facultet_idFacultet` INT NOT NULL,
  `Nazvanie gryppi` VARCHAR(45) NULL,
  `Yspevaemost_idYspevaemost` INT NOT NULL,
  `Yspevaemost_Disciplini_idDisciplini` INT NOT NULL,
  PRIMARY KEY (`idGryppi`, `Facultet_idFacultet`, `Yspevaemost_idYspevaemost`, `Yspevaemost_Disciplini_idDisciplini`),
  INDEX `fk_Gryppi_Facultet1_idx` (`Facultet_idFacultet` ASC) VISIBLE,
  INDEX `fk_Gryppi_Yspevaemost1_idx` (`Yspevaemost_idYspevaemost` ASC, `Yspevaemost_Disciplini_idDisciplini` ASC) VISIBLE,
  CONSTRAINT `fk_Gryppi_Facultet1`
    FOREIGN KEY (`Facultet_idFacultet`)
    REFERENCES `mydb`.`Facultet` (`idFacultet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gryppi_Yspevaemost1`
    FOREIGN KEY (`Yspevaemost_idYspevaemost` , `Yspevaemost_Disciplini_idDisciplini`)
    REFERENCES `mydb`.`Yspevaemost` (`idYspevaemost` , `Disciplini_idDisciplini`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Norma dlya prepodavateley na gruppy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Norma dlya prepodavateley na gruppy` (
  `idNorma` INT NOT NULL,
  `Familiya prepodavatelya` VARCHAR(45) NULL,
  `Name prepodovatelya` VARCHAR(45) NULL,
  `Otchestvo prepodavatelya` VARCHAR(45) NULL,
  `Gryppa` VARCHAR(45) NULL,
  `Disciplina` VARCHAR(45) NULL,
  `Norma chasov` VARCHAR(45) NULL,
  `Prepodavateli_idPrepodavateli` INT NOT NULL,
  `Gryppi_idGryppi` INT NOT NULL,
  PRIMARY KEY (`idNorma`, `Prepodavateli_idPrepodavateli`, `Gryppi_idGryppi`),
  INDEX `fk_Norma dlya prepodavateley na gruppy_Prepodavateli1_idx` (`Prepodavateli_idPrepodavateli` ASC) VISIBLE,
  INDEX `fk_Norma dlya prepodavateley na gruppy_Gryppi1_idx` (`Gryppi_idGryppi` ASC) VISIBLE,
  CONSTRAINT `fk_Norma dlya prepodavateley na gruppy_Prepodavateli1`
    FOREIGN KEY (`Prepodavateli_idPrepodavateli`)
    REFERENCES `mydb`.`Prepodavateli` (`idPrepodavateli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Norma dlya prepodavateley na gruppy_Gryppi1`
    FOREIGN KEY (`Gryppi_idGryppi`)
    REFERENCES `mydb`.`Gryppi` (`idGryppi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Naznachenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Naznachenie` (
  `Prepodavateli_idPrepodavateli` INT NOT NULL,
  `Disciplini_idDisciplini` INT NOT NULL,
  PRIMARY KEY (`Prepodavateli_idPrepodavateli`, `Disciplini_idDisciplini`),
  INDEX `fk_Naznachenie_Prepodavateli1_idx` (`Prepodavateli_idPrepodavateli` ASC) VISIBLE,
  CONSTRAINT `fk_Naznachenie_Disciplini`
    FOREIGN KEY (`Disciplini_idDisciplini`)
    REFERENCES `mydb`.`Disciplini` (`idDisciplini`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Naznachenie_Prepodavateli1`
    FOREIGN KEY (`Prepodavateli_idPrepodavateli`)
    REFERENCES `mydb`.`Prepodavateli` (`idPrepodavateli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studenti` (
  `idStudenta` INT NOT NULL,
  `Gryppi_idGryppi` INT NOT NULL,
  `Familiya` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Otchestvo` VARCHAR(45) NULL,
  `Pol` VARCHAR(45) NULL,
  `Data rozhdenya` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  `Seriya pasporta` VARCHAR(45) NULL,
  `Nomer pasporta` VARCHAR(45) NULL,
  `Kem vidan` VARCHAR(45) NULL,
  `Data vidachi` VARCHAR(45) NULL,
  `Voennaya obyazonast` VARCHAR(45) NULL,
  `Data postupleniya` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudenta`, `Gryppi_idGryppi`),
  INDEX `fk_Studenti_Gryppi1_idx` (`Gryppi_idGryppi` ASC) VISIBLE,
  CONSTRAINT `fk_Studenti_Gryppi1`
    FOREIGN KEY (`Gryppi_idGryppi`)
    REFERENCES `mydb`.`Gryppi` (`idGryppi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ycheba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ycheba` (
  `Disciplini_idDisciplini` INT NOT NULL,
  `Studenti_idStudenta` INT NOT NULL,
  PRIMARY KEY (`Disciplini_idDisciplini`, `Studenti_idStudenta`),
  INDEX `fk_Ycheba_Studenti1_idx` (`Studenti_idStudenta` ASC) VISIBLE,
  CONSTRAINT `fk_Ycheba_Disciplini1`
    FOREIGN KEY (`Disciplini_idDisciplini`)
    REFERENCES `mydb`.`Disciplini` (`idDisciplini`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ycheba_Studenti1`
    FOREIGN KEY (`Studenti_idStudenta`)
    REFERENCES `mydb`.`Studenti` (`idStudenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Obrazovanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Obrazovanie` (
  `idObrazovaniya` INT NOT NULL,
  `Studenti_idStudenta` INT NOT NULL,
  `Obrazovanie` VARCHAR(45) NULL,
  `Naimenovanie uchebnogo zavedenya` VARCHAR(45) NULL,
  `God okonchaniya` VARCHAR(45) NULL,
  `Seriya documentov` VARCHAR(45) NULL,
  `Nomer documenta` VARCHAR(45) NULL,
  PRIMARY KEY (`idObrazovaniya`, `Studenti_idStudenta`),
  INDEX `fk_Obrazovanie_Studenti1_idx` (`Studenti_idStudenta` ASC) VISIBLE,
  CONSTRAINT `fk_Obrazovanie_Studenti1`
    FOREIGN KEY (`Studenti_idStudenta`)
    REFERENCES `mydb`.`Studenti` (`idStudenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`id` (
  `idPrepodavateli` INT NULL,
  `idNorma` VARCHAR(45) NULL,
  `idDisciplini` VARCHAR(45) NULL,
  `idFacultet` VARCHAR(45) NULL,
  `idStudenta` VARCHAR(45) NULL,
  `idYspevaemost` VARCHAR(45) NULL,
  `idObrazovanie` VARCHAR(45) NULL,
  `Prepodavateli_idPrepodavateli` INT NOT NULL,
  PRIMARY KEY (`Prepodavateli_idPrepodavateli`),
  CONSTRAINT `fk_id_Prepodavateli1`
    FOREIGN KEY (`Prepodavateli_idPrepodavateli`)
    REFERENCES `mydb`.`Prepodavateli` (`idPrepodavateli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`id_has_Prepodavateli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`id_has_Prepodavateli` (
  `id_Prepodavateli_idPrepodavateli` INT NOT NULL,
  `Prepodavateli_idPrepodavateli` INT NOT NULL,
  PRIMARY KEY (`id_Prepodavateli_idPrepodavateli`, `Prepodavateli_idPrepodavateli`),
  INDEX `fk_id_has_Prepodavateli_Prepodavateli1_idx` (`Prepodavateli_idPrepodavateli` ASC) VISIBLE,
  INDEX `fk_id_has_Prepodavateli_id1_idx` (`id_Prepodavateli_idPrepodavateli` ASC) VISIBLE,
  CONSTRAINT `fk_id_has_Prepodavateli_id1`
    FOREIGN KEY (`id_Prepodavateli_idPrepodavateli`)
    REFERENCES `mydb`.`id` (`Prepodavateli_idPrepodavateli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_has_Prepodavateli_Prepodavateli1`
    FOREIGN KEY (`Prepodavateli_idPrepodavateli`)
    REFERENCES `mydb`.`Prepodavateli` (`idPrepodavateli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
